import { ShortVideo } from '@/types';

export const shortsData: ShortVideo[] = [
  {
    id: '1',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    title: 'Big Buck Bunny',
    description: 'A delightful animated adventure featuring a large rabbit dealing with mischievous flying creatures in a vibrant forest setting.',
    tags: ['animation', 'nature', 'adventure', 'animals'],
    duration: 30,
    likes: 1247,
  },
  {
    id: '2',
    videoUrl: 'https://samplelib.com/lib/preview/mp4/sample-5s.mp4',
    title: 'Quick Sample',
    description: 'A brief cinematic moment capturing the essence of modern video technology and digital storytelling.',
    tags: ['tech', 'demo', 'short'],
    duration: 5,
    likes: 892,
  },
  {
    id: '3',
    videoUrl: 'https://samplelib.com/lib/preview/mp4/sample-10s.mp4',
    title: 'Ten Second Wonder',
    description: 'Experience ten seconds of carefully crafted visual content designed to showcase smooth playback.',
    tags: ['demo', 'tech', 'cinematic'],
    duration: 10,
    likes: 2156,
  },
  {
    id: '4',
    videoUrl: 'https://samplelib.com/lib/preview/mp4/sample-15s.mp4',
    title: 'Quick Escape',
    description: 'A short journey through time and space, perfect for testing video streaming capabilities.',
    tags: ['adventure', 'demo', 'scenic'],
    duration: 15,
    likes: 1678,
  },
  {
    id: '5',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    title: 'Big Buck Bunny: Full Adventure',
    description: 'The complete story of a giant rabbit and his forest friends in this charming open-source animated short film.',
    tags: ['animation', 'nature', 'animals', 'adventure'],
    duration: 596,
    likes: 3421,
  },
  {
    id: '6',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    title: 'Elephants Dream',
    description: 'A surreal science fiction journey through a mechanical world, exploring themes of reality and perception.',
    tags: ['animation', 'sci-fi', 'artistic', 'adventure'],
    duration: 653,
    likes: 2834,
  },
  {
    id: '7',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    title: 'For Bigger Blazes',
    description: 'An intense showcase of fire and energy, demonstrating the power of high-quality video streaming.',
    tags: ['action', 'demo', 'cinematic', 'intense'],
    duration: 15,
    likes: 1923,
  },
  {
    id: '8',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    title: 'For Bigger Escapes',
    description: 'Embark on a visual journey showcasing breathtaking landscapes and the freedom of exploration.',
    tags: ['nature', 'scenic', 'adventure', 'relaxing'],
    duration: 15,
    likes: 2567,
  },
  {
    id: '9',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    title: 'For Bigger Fun',
    description: 'A vibrant celebration of joy and entertainment, perfect for uplifting your spirits.',
    tags: ['fun', 'urban', 'energetic', 'entertainment'],
    duration: 60,
    likes: 3102,
  },
  {
    id: '10',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    title: 'For Bigger Joyrides',
    description: 'Experience the thrill of the ride with stunning visuals and dynamic camera work.',
    tags: ['action', 'adventure', 'urban', 'exciting'],
    duration: 15,
    likes: 2890,
  },
];